-
  os: Visual Studio 2015
  configuration: Release
  skip_tags: true
  
  branches:
    only:
      - master

  version: 1.5.{build}
  pull_requests:
    do_not_increment_build_number: true


  install:

  - ps: >-

      (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

  before_build:
    - ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion
    - ps: Vsix-TokenReplacement GitSccProvider\source.extension.cs 'Version = "([0-9\\.]+)"' 'Version = "{version}"'

  build_script:
    - nuget restore -Verbosity quiet
    - msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m
  test: off
  artifacts:
  - path: GitSccProvider\bin\Release\GitSccProvider.vsix
    name: GitSccProvider


  deploy:
    release: Release $(appveyor_build_version)
    description: GSCP Release Build -v$(appveyor_build_version)
    provider: GitHub
    auth_token:
      secure: D9+WTOpCzI8qcrBNULSrWHJeR4thDu4jxQmY/oHux1CYpAjfk2rrpShn8loWHGQc # your encrypted token from GitHub
    artifact: GitSccProvider\bin\Release\GitSccProvider.vsix           # upload all NuGet packages to release assets
    draft: false
    prerelease: false